### ISSUE TITLE
"Error in if (unique(out$stats.videoCount) == 0) { :    argument is of length zero" while using trends query

### ISSUE THREAD

**Issue by n8carp81** [benjaminguinaudeau/tiktokr#10]
While running `trends <- tk_posts(scope = "trends", n = 100)` I receive the following error:

Error in if (unique(out$stats.videoCount) == 0) { : 
  argument is of length zero

**Comment by benjaminguinaudeau** [comment]
I overlooked your issue, sorry for that. 

Tiktok changed its API and the trend endpoint might be affected. I'll look into it and will try to get the trend endpoint to work again. Sorry for the inconvenience.

**Comment by benjaminguinaudeau** [comment]
Hello, 

The last push should have solved this issue, so I'll close it. Don't hesitate to reopen it, if the issue persists.
