### ISSUE TITLE
No module named 'requests' when initiating tiktokr

### ISSUE THREAD

**Issue by adamkthecoder** [benjaminguinaudeau/tiktokr#12]
Wondering if anybody has feedback on this. When I try initiating tik tokr, I am getting an error that says: 

Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'requests'

Detailed traceback: 
  File "<string>", line 8, in <module>
  File "/Users/.../Library/R/4.0/library/reticulate/python/rpytools/loader.py", line 24, in _import_hook
    level=level

**Comment by stevesteve2** [comment]
I tried this: 
py_install("requests", pip = TRUE)
And it worked. 

(Though it stopped working about a week ago, so I have other problems...)

**Comment by adamkthecoder** [comment]
Thank you so much! It worked!
